// // [
// //   {
// //     "propertyId": "01K439YFVGN2Z0D834ZZJXY6YW",
// //     "code": "AB",
// //     "propertyName": "This is a Test Property#2",
// //     "transactionType": "LEASE",
// //     "spaceType": "MIXED",
// //     "propertyCountry": "AE",
// //     "sellingCurrency": "AED",
// //     "uomCode": "SFT",
// //     "city": null,
// //     "district": null,
// //     "communityName": null,
// //     "legalEntitySeller": "The P Company LLC",
// //     "escrowBankAccountId": "01K3RWVPQW061PV75XXHKTAWWY",
// //     "corpBankAccountId": "01K3WXE2QY5WKF454XQ3PYN4ND",
// //     "anCompDate": "10-01-2030",
// //     "areaVariancePc": 5,
// //     "permitDate": "01-01-2025",
// //     "launchDate": "10-09-2025",
// //     "registrationPrecent": 4,
// //     "propertyAttributes": {
// //       "plotArea": 10000,
// //       "longitude": 56.7888888,
// //       "parcelNumber": "1122"
// //     },
// //     "attributeList": null,
// //     "parentPropertyId": null,
// //     "countryName": "United Arab Emirates",
// //     "propertyLocation": "The Excellent Community|Mankhool|Dubai|United Arab Emirates",
// //     "legalEntityDeveloper": "P Developer",
// //     "escrowBank": "1-121-112121|HDFC Bank|Bur Dubai|Dubai",
// //     "corporateBank": "EN-1111112|ENBD Bank|Bur Dubai|Dubai",
// //     "createdAt": "01-09-2025 22:52",
// //     "updatedAt": "01-09-2025 22:52",
// //     "createdBy": "sasanka.rath",
// //     "updatedBy": "sasanka.rath"
// //   },
// //   {
// //     "propertyId": "01K439NEC8245BXSKWXPJRR5KZ",
// //     "code": "AB",
// //     "propertyName": "This is a Test Property#2",
// //     "transactionType": "LEASE",
// //     "spaceType": "MIXED",
// //     "propertyCountry": "AE",
// //     "sellingCurrency": "AED",
// //     "uomCode": "SFT",
// //     "city": null,
// //     "district": null,
// //     "communityName": null,
// //     "legalEntitySeller": "The P Company LLC",
// //     "escrowBankAccountId": "01K3RWVPQW061PV75XXHKTAWWY",
// //     "corpBankAccountId": "01K3WXE2QY5WKF454XQ3PYN4ND",
// //     "anCompDate": "10-01-2030",
// //     "areaVariancePc": 5,
// //     "permitDate": "01-01-2025",
// //     "launchDate": "10-09-2025",
// //     "registrationPrecent": 4,
// //     "propertyAttributes": {
// //       "longitude": 56.7888888,
// //       "parcelNumber": "1122"
// //     },
// //     "attributeList": null,
// //     "parentPropertyId": null,
// //     "countryName": "United Arab Emirates",
// //     "propertyLocation": "The Excellent Community|Mankhool|Dubai|United Arab Emirates",
// //     "legalEntityDeveloper": "P Developer",
// //     "escrowBank": "1-121-112121|HDFC Bank|Bur Dubai|Dubai",
// //     "corporateBank": "EN-1111112|ENBD Bank|Bur Dubai|Dubai",
// //     "createdAt": "01-09-2025 22:47",
// //     "updatedAt": "01-09-2025 22:47",
// //     "createdBy": null,
// //     "updatedBy": null
// //   },
// //   {
// //     "propertyId": "01K439RY7AYK7AFKFCMGKNDDEG",
// //     "code": "AB",
// //     "propertyName": "This is a Test Property#2",
// //     "transactionType": "LEASE",
// //     "spaceType": "MIXED",
// //     "propertyCountry": "AE",
// //     "sellingCurrency": "AED",
// //     "uomCode": "SFT",
// //     "city": null,
// //     "district": null,
// //     "communityName": null,
// //     "legalEntitySeller": "The P Company LLC",
// //     "escrowBankAccountId": "01K3RWVPQW061PV75XXHKTAWWY",
// //     "corpBankAccountId": "01K3WXE2QY5WKF454XQ3PYN4ND",
// //     "anCompDate": "10-01-2030",
// //     "areaVariancePc": 5,
// //     "permitDate": "01-01-2025",
// //     "launchDate": "10-09-2025",
// //     "registrationPrecent": 4,
// //     "propertyAttributes": {
// //       "longitude": 56.7888888,
// //       "parcelNumber": "1122"
// //     },
// //     "attributeList": null,
// //     "parentPropertyId": null,
// //     "countryName": "United Arab Emirates",
// //     "propertyLocation": "The Excellent Community|Mankhool|Dubai|United Arab Emirates",
// //     "legalEntityDeveloper": "P Developer",
// //     "escrowBank": "1-121-112121|HDFC Bank|Bur Dubai|Dubai",
// //     "corporateBank": "EN-1111112|ENBD Bank|Bur Dubai|Dubai",
// //     "createdAt": "01-09-2025 22:49",
// //     "updatedAt": "01-09-2025 22:49",
// //     "createdBy": null,
// //     "updatedBy": null
// //   },
// //   {
// //     "propertyId": "01K439VEGAHBMZQ0HNJN04KAA2",
// //     "code": "AB",
// //     "propertyName": "This is a Test Property#2",
// //     "transactionType": "LEASE",
// //     "spaceType": "MIXED",
// //     "propertyCountry": "AE",
// //     "sellingCurrency": "AED",
// //     "uomCode": "SFT",
// //     "city": null,
// //     "district": null,
// //     "communityName": null,
// //     "legalEntitySeller": "The P Company LLC",
// //     "escrowBankAccountId": "01K3RWVPQW061PV75XXHKTAWWY",
// //     "corpBankAccountId": "01K3WXE2QY5WKF454XQ3PYN4ND",
// //     "anCompDate": "10-01-2030",
// //     "areaVariancePc": 5,
// //     "permitDate": "01-01-2025",
// //     "launchDate": "10-09-2025",
// //     "registrationPrecent": 4,
// //     "propertyAttributes": {
// //       "longitude": 56.7888888,
// //       "parcelNumber": "1122"
// //     },
// //     "attributeList": null,
// //     "parentPropertyId": null,
// //     "countryName": "United Arab Emirates",
// //     "propertyLocation": "The Excellent Community|Mankhool|Dubai|United Arab Emirates",
// //     "legalEntityDeveloper": "P Developer",
// //     "escrowBank": "1-121-112121|HDFC Bank|Bur Dubai|Dubai",
// //     "corporateBank": "EN-1111112|ENBD Bank|Bur Dubai|Dubai",
// //     "createdAt": "01-09-2025 22:50",
// //     "updatedAt": "01-09-2025 22:50",
// //     "createdBy": null,
// //     "updatedBy": null
// //   },
// //   {
// //     "propertyId": "01K4394QRQKW3AG3PHF6XF9M2R",
// //     "code": "GH",
// //     "propertyName": "171 Garden Heights",
// //     "transactionType": "SALE",
// //     "spaceType": "RESIDENTIAL",
// //     "propertyCountry": "AE",
// //     "sellingCurrency": "AED",
// //     "uomCode": "SFT",
// //     "city": null,
// //     "district": null,
// //     "communityName": null,
// //     "legalEntitySeller": "J Global PLC",
// //     "escrowBankAccountId": "01K3RXV7F5N9TKRFJFP17FYYP3",
// //     "corpBankAccountId": "01K3RY38T8M3G0TT3F6QV04WWX",
// //     "anCompDate": "31-12-2029",
// //     "areaVariancePc": 5,
// //     "permitDate": "01-01-2025",
// //     "launchDate": "01-09-2025",
// //     "registrationPrecent": 4,
// //     "propertyAttributes": {
// //       "longitude": 56.7888888,
// //       "parcelNumber": "1122"
// //     },
// //     "attributeList": null,
// //     "parentPropertyId": null,
// //     "countryName": "United Arab Emirates",
// //     "propertyLocation": "The unique Community|Jumera|Dubai|United Arab Emirates",
// //     "legalEntityDeveloper": "J Global PLC",
// //     "escrowBank": "1-121-1121X1|Mashreq Bank|Bur Dubai|Dubai",
// //     "corporateBank": "1-121-1121Y1|ENBD|Bur Dubai|Dubai",
// //     "createdAt": "19-08-2025 00:00",
// //     "updatedAt": "19-08-2025 18:00",
// //     "createdBy": "sasanka.rath",
// //     "updatedBy": "sasanka.rath"
// //   },
// //   {
// //     "propertyId": "01K4393G11EAD8XS05HCECY188",
// //     "code": "SA",
// //     "propertyName": "SkyHills Astra",
// //     "transactionType": "SALE",
// //     "spaceType": "RESIDENTIAL",
// //     "propertyCountry": "AE",
// //     "sellingCurrency": "AED",
// //     "uomCode": "SQM",
// //     "city": null,
// //     "district": null,
// //     "communityName": null,
// //     "legalEntitySeller": "J Global PLC",
// //     "escrowBankAccountId": "01K3RY38T8M3G0TT3F6QV04WWX",
// //     "corpBankAccountId": "01K3RY38T8M3G0TT3F6QV04WWX",
// //     "anCompDate": "31-12-2029",
// //     "areaVariancePc": 5,
// //     "permitDate": "01-01-2025",
// //     "launchDate": "01-09-2025",
// //     "registrationPrecent": 4,
// //     "propertyAttributes": {
// //       "longitude": 56.7888888,
// //       "parcelNumber": "1122"
// //     },
// //     "attributeList": null,
// //     "parentPropertyId": null,
// //     "countryName": "United Arab Emirates",
// //     "propertyLocation": "The unique Community|Dubai|United Arab Emirates",
// //     "legalEntityDeveloper": "J Global PLC",
// //     "escrowBank": "1-121-1121Y1|ENBD|Bur Dubai|Dubai",
// //     "corporateBank": "1-121-1121Y1|ENBD|Bur Dubai|Dubai",
// //     "createdAt": "19-08-2025 00:00",
// //     "updatedAt": "19-08-2025 18:00",
// //     "createdBy": "sasanka.rath",
// //     "updatedBy": "sasanka.rath"
// //   }
// // ]

// {
//     "propertyId": "01K439YFVGN2Z0D834ZZJXY6YW",
//     "code": "AB",
//     "propertyName": "This is a Test Property#2",
//     "transactionType": "LEASE",
//     "spaceType": "MIXED",
//     "propertyCountry": "AE",
//     "sellingCurrency": "AED",
//     "uomCode": "SFT",
//     "city": "Dubai",
//     "district": "Dubai",
//     "communityName": "MARINE",
//     "legalEntitySeller": "The P Company LLC",
//     "escrowBankAccountId": "01K3RWVPQW061PV75XXHKTAWWY",
//     "corpBankAccountId": "01K3WXE2QY5WKF454XQ3PYN4ND",
//     "anCompDate": "2030-09-30T20:00:00.000Z",
//     "areaVariancePc": 5,
//     "permitDate": "2024-12-31T20:00:00.000Z",
//     "launchDate": "2025-10-08T20:00:00.000Z",
//     "registrationPrecent": 4,
//     "propertyAttributes": {
//         "plotArea": 10000,
//         "longitude": 56.7888888,
//         "parcelNumber": "1122"
//     },
//     "attributeList": null,
//     "parentPropertyId": null,
//     "countryName": "United Arab Emirates",
//     "propertyLocation": "The Excellent Community|Mankhool|Dubai|United Arab Emirates",
//     "legalEntityDeveloper": "P Developer",
//     "escrowBank": "1-121-112121|HDFC Bank|Bur Dubai|Dubai",
//     "corporateBank": "EN-1111112|ENBD Bank|Bur Dubai|Dubai",
//     "createdAt": "01-09-2025 22:52",
//     "updatedAt": "01-09-2025 22:52",
//     "createdBy": "sasanka.rath",
//     "updatedBy": "sasanka.rath",
//     "parcelNumber": "202302",
//     "latitude": "324234",
//     "longitude": "234322",
//     "grossFloorArea": "34234243",
//     "plotArea": null,
//     "plotNumber": "234",
//     "registrationPercent": null,
//     "country": "United Arab Emirates",
//     "countryCode": "AE"
// }


{
    "code": "AB",
    "propertyName": "This is a Test Property#2",
    "transactionType": "MIXED",
    "spaceType": "MIXED",
    "propertyCountry": "AE",
    "sellingCurrency": "AED",
    "uomCode": "SQM",
    "city": "DUbai",
    "district": "Dubai",
    "communityName": "community",
    "legalEntitySeller": "The P Company LLC",
    "escrowBankAccountId": "01K3RWVPQW061PV75XXHKTAWWY",
    "corpBankAccountId": "01K3WXE2QY5WKF454XQ3PYN4ND",
    "anCompDate": "2030-09-30T20:00:00.000Z",
    "areaVariancePc": 5,
    "permitDate": "2024-12-31T20:00:00.000Z",
    "launchDate": "2025-10-08T20:00:00.000Z",
    "registrationPrecent": 4,
    "propertyAttributes": {
        "plotArea": 10000,
        "longitude": 56.7888888,
        "parcelNumber": "1122"
    },
    "countryName": "United Arab Emirates",
    "propertyLocation": "The Excellent Community|Mankhool|Dubai|United Arab Emirates",
    "legalEntityDeveloper": "P Developer",
    "createdAt": "01-09-2025 22:52",
    "updatedAt": "01-09-2025 22:52",
    "createdBy": "sasanka.rath",
    "updatedBy": "sasanka.rath",
    "registrationPercent": "4234",
    "country": "United Arab Emirates",
    "countryCode": "AE",
    "parcelNumber": null,
    "latitude": null,
    "longitude": null,
    "grossFloorArea": null,
    "plotArea": null,
    "plotNumber": null
}